my_first_dbt_project:
  target: dev
  outputs:
    dev:
      account: MQVLHJZ-GW27152
      database: dbt_learning
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: SYSADMIN
      schema: nagarjuna
      threads: 4
      type: snowflake
      user: NANDU897764
      warehouse: COMPUTE_WH

    prod:
      account:  MQVLHJZ-GW27152
      database: analytics
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: SYSADMIN
      schema: public
      threads: 4
      type: snowflake
      user: NANDU897764
      warehouse: COMPUTE_WH,

    ci:
      account: MQVLHJZ-GW27152
      database: analytics_{{ env_var('DBT_PR_NUMBER')}}
      password: YOUR_PASSWORD_HERE
      role: SYSADMIN
      schema: public
      threads: 4
      type: snowflake
      user: NANDU897764
      warehouse: COMPUTE_WH